--- #YAML:1.0
name:                BerkeleyDB-Manager
version:             0.06
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    BerkeleyDB:                    0
    Data::Stream::Bulk:            0
    Moose:                         0
    namespace::clean:              0.08
    Path::Class:                   0
    Test::Exception:               0
    Test::TempDir:                 0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
